apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: test python app.
  annotations:
     github.com/project-slug: limbuhimal/python-app

spec:
  type: service
  owner: development
  lifecycle: experimental